// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalanceledger"
)

// UserBalanceLedgerUpdate is the builder for updating UserBalanceLedger entities.
type UserBalanceLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *UserBalanceLedgerMutation
}

// Where appends a list predicates to the UserBalanceLedgerUpdate builder.
func (_u *UserBalanceLedgerUpdate) Where(ps ...predicate.UserBalanceLedger) *UserBalanceLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBalanceLedgerUpdate) SetUpdatedAt(v time.Time) *UserBalanceLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserBalanceLedgerUpdate) SetUserID(v int64) *UserBalanceLedgerUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableUserID(v *int64) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *UserBalanceLedgerUpdate) SetOrderID(v int64) *UserBalanceLedgerUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableOrderID(v *int64) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *UserBalanceLedgerUpdate) SetEntryType(v string) *UserBalanceLedgerUpdate {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableEntryType(v *string) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *UserBalanceLedgerUpdate) SetDirection(v string) *UserBalanceLedgerUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableDirection(v *string) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserBalanceLedgerUpdate) SetAmount(v float64) *UserBalanceLedgerUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableAmount(v *float64) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserBalanceLedgerUpdate) AddAmount(v float64) *UserBalanceLedgerUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *UserBalanceLedgerUpdate) SetBalanceAfter(v float64) *UserBalanceLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableBalanceAfter(v *float64) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *UserBalanceLedgerUpdate) AddBalanceAfter(v float64) *UserBalanceLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetMemo sets the "memo" field.
func (_u *UserBalanceLedgerUpdate) SetMemo(v string) *UserBalanceLedgerUpdate {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableMemo(v *string) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *UserBalanceLedgerUpdate) ClearMemo() *UserBalanceLedgerUpdate {
	_u.mutation.ClearMemo()
	return _u
}

// SetFrozen sets the "frozen" field.
func (_u *UserBalanceLedgerUpdate) SetFrozen(v bool) *UserBalanceLedgerUpdate {
	_u.mutation.SetFrozen(v)
	return _u
}

// SetNillableFrozen sets the "frozen" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableFrozen(v *bool) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetFrozen(*v)
	}
	return _u
}

// SetRefundBatchID sets the "refund_batch_id" field.
func (_u *UserBalanceLedgerUpdate) SetRefundBatchID(v string) *UserBalanceLedgerUpdate {
	_u.mutation.SetRefundBatchID(v)
	return _u
}

// SetNillableRefundBatchID sets the "refund_batch_id" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdate) SetNillableRefundBatchID(v *string) *UserBalanceLedgerUpdate {
	if v != nil {
		_u.SetRefundBatchID(*v)
	}
	return _u
}

// ClearRefundBatchID clears the value of the "refund_batch_id" field.
func (_u *UserBalanceLedgerUpdate) ClearRefundBatchID() *UserBalanceLedgerUpdate {
	_u.mutation.ClearRefundBatchID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBalanceLedgerUpdate) SetUser(v *User) *UserBalanceLedgerUpdate {
	return _u.SetUserID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *UserBalanceLedgerUpdate) SetOrder(v *PaymentOrder) *UserBalanceLedgerUpdate {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the UserBalanceLedgerMutation object of the builder.
func (_u *UserBalanceLedgerUpdate) Mutation() *UserBalanceLedgerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBalanceLedgerUpdate) ClearUser() *UserBalanceLedgerUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *UserBalanceLedgerUpdate) ClearOrder() *UserBalanceLedgerUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserBalanceLedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBalanceLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserBalanceLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBalanceLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBalanceLedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbalanceledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBalanceLedgerUpdate) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := userbalanceledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := userbalanceledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundBatchID(); ok {
		if err := userbalanceledger.RefundBatchIDValidator(v); err != nil {
			return &ValidationError{Name: "refund_batch_id", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.refund_batch_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBalanceLedger.user"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBalanceLedger.order"`)
	}
	return nil
}

func (_u *UserBalanceLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbalanceledger.Table, userbalanceledger.Columns, sqlgraph.NewFieldSpec(userbalanceledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalanceledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(userbalanceledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(userbalanceledger.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(userbalanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(userbalanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(userbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(userbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(userbalanceledger.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(userbalanceledger.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.Frozen(); ok {
		_spec.SetField(userbalanceledger.FieldFrozen, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefundBatchID(); ok {
		_spec.SetField(userbalanceledger.FieldRefundBatchID, field.TypeString, value)
	}
	if _u.mutation.RefundBatchIDCleared() {
		_spec.ClearField(userbalanceledger.FieldRefundBatchID, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.UserTable,
			Columns: []string{userbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.UserTable,
			Columns: []string{userbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.OrderTable,
			Columns: []string{userbalanceledger.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.OrderTable,
			Columns: []string{userbalanceledger.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbalanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserBalanceLedgerUpdateOne is the builder for updating a single UserBalanceLedger entity.
type UserBalanceLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserBalanceLedgerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserBalanceLedgerUpdateOne) SetUpdatedAt(v time.Time) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserBalanceLedgerUpdateOne) SetUserID(v int64) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableUserID(v *int64) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *UserBalanceLedgerUpdateOne) SetOrderID(v int64) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableOrderID(v *int64) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *UserBalanceLedgerUpdateOne) SetEntryType(v string) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableEntryType(v *string) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *UserBalanceLedgerUpdateOne) SetDirection(v string) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableDirection(v *string) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *UserBalanceLedgerUpdateOne) SetAmount(v float64) *UserBalanceLedgerUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableAmount(v *float64) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *UserBalanceLedgerUpdateOne) AddAmount(v float64) *UserBalanceLedgerUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *UserBalanceLedgerUpdateOne) SetBalanceAfter(v float64) *UserBalanceLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableBalanceAfter(v *float64) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *UserBalanceLedgerUpdateOne) AddBalanceAfter(v float64) *UserBalanceLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetMemo sets the "memo" field.
func (_u *UserBalanceLedgerUpdateOne) SetMemo(v string) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableMemo(v *string) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *UserBalanceLedgerUpdateOne) ClearMemo() *UserBalanceLedgerUpdateOne {
	_u.mutation.ClearMemo()
	return _u
}

// SetFrozen sets the "frozen" field.
func (_u *UserBalanceLedgerUpdateOne) SetFrozen(v bool) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetFrozen(v)
	return _u
}

// SetNillableFrozen sets the "frozen" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableFrozen(v *bool) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetFrozen(*v)
	}
	return _u
}

// SetRefundBatchID sets the "refund_batch_id" field.
func (_u *UserBalanceLedgerUpdateOne) SetRefundBatchID(v string) *UserBalanceLedgerUpdateOne {
	_u.mutation.SetRefundBatchID(v)
	return _u
}

// SetNillableRefundBatchID sets the "refund_batch_id" field if the given value is not nil.
func (_u *UserBalanceLedgerUpdateOne) SetNillableRefundBatchID(v *string) *UserBalanceLedgerUpdateOne {
	if v != nil {
		_u.SetRefundBatchID(*v)
	}
	return _u
}

// ClearRefundBatchID clears the value of the "refund_batch_id" field.
func (_u *UserBalanceLedgerUpdateOne) ClearRefundBatchID() *UserBalanceLedgerUpdateOne {
	_u.mutation.ClearRefundBatchID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBalanceLedgerUpdateOne) SetUser(v *User) *UserBalanceLedgerUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *UserBalanceLedgerUpdateOne) SetOrder(v *PaymentOrder) *UserBalanceLedgerUpdateOne {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the UserBalanceLedgerMutation object of the builder.
func (_u *UserBalanceLedgerUpdateOne) Mutation() *UserBalanceLedgerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBalanceLedgerUpdateOne) ClearUser() *UserBalanceLedgerUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *UserBalanceLedgerUpdateOne) ClearOrder() *UserBalanceLedgerUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Where appends a list predicates to the UserBalanceLedgerUpdate builder.
func (_u *UserBalanceLedgerUpdateOne) Where(ps ...predicate.UserBalanceLedger) *UserBalanceLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserBalanceLedgerUpdateOne) Select(field string, fields ...string) *UserBalanceLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserBalanceLedger entity.
func (_u *UserBalanceLedgerUpdateOne) Save(ctx context.Context) (*UserBalanceLedger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBalanceLedgerUpdateOne) SaveX(ctx context.Context) *UserBalanceLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserBalanceLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBalanceLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserBalanceLedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userbalanceledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBalanceLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := userbalanceledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := userbalanceledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.direction": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundBatchID(); ok {
		if err := userbalanceledger.RefundBatchIDValidator(v); err != nil {
			return &ValidationError{Name: "refund_batch_id", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.refund_batch_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBalanceLedger.user"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBalanceLedger.order"`)
	}
	return nil
}

func (_u *UserBalanceLedgerUpdateOne) sqlSave(ctx context.Context) (_node *UserBalanceLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbalanceledger.Table, userbalanceledger.Columns, sqlgraph.NewFieldSpec(userbalanceledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserBalanceLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbalanceledger.FieldID)
		for _, f := range fields {
			if !userbalanceledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userbalanceledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalanceledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(userbalanceledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(userbalanceledger.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(userbalanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(userbalanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(userbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(userbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(userbalanceledger.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(userbalanceledger.FieldMemo, field.TypeString)
	}
	if value, ok := _u.mutation.Frozen(); ok {
		_spec.SetField(userbalanceledger.FieldFrozen, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefundBatchID(); ok {
		_spec.SetField(userbalanceledger.FieldRefundBatchID, field.TypeString, value)
	}
	if _u.mutation.RefundBatchIDCleared() {
		_spec.ClearField(userbalanceledger.FieldRefundBatchID, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.UserTable,
			Columns: []string{userbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.UserTable,
			Columns: []string{userbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.OrderTable,
			Columns: []string{userbalanceledger.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.OrderTable,
			Columns: []string{userbalanceledger.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserBalanceLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbalanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
