// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalanceledger"
)

// UserBalanceLedger is the model entity for the UserBalanceLedger schema.
type UserBalanceLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// EntryType holds the value of the "entry_type" field.
	EntryType string `json:"entry_type,omitempty"`
	// Direction holds the value of the "direction" field.
	Direction string `json:"direction,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter float64 `json:"balance_after,omitempty"`
	// Memo holds the value of the "memo" field.
	Memo *string `json:"memo,omitempty"`
	// Frozen holds the value of the "frozen" field.
	Frozen bool `json:"frozen,omitempty"`
	// RefundBatchID holds the value of the "refund_batch_id" field.
	RefundBatchID *string `json:"refund_batch_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserBalanceLedgerQuery when eager-loading is set.
	Edges        UserBalanceLedgerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserBalanceLedgerEdges holds the relations/edges for other nodes in the graph.
type UserBalanceLedgerEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Order holds the value of the order edge.
	Order *PaymentOrder `json:"order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBalanceLedgerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserBalanceLedgerEdges) OrderOrErr() (*PaymentOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserBalanceLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userbalanceledger.FieldFrozen:
			values[i] = new(sql.NullBool)
		case userbalanceledger.FieldAmount, userbalanceledger.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case userbalanceledger.FieldID, userbalanceledger.FieldUserID, userbalanceledger.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case userbalanceledger.FieldEntryType, userbalanceledger.FieldDirection, userbalanceledger.FieldMemo, userbalanceledger.FieldRefundBatchID:
			values[i] = new(sql.NullString)
		case userbalanceledger.FieldCreatedAt, userbalanceledger.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserBalanceLedger fields.
func (_m *UserBalanceLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userbalanceledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userbalanceledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userbalanceledger.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userbalanceledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userbalanceledger.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case userbalanceledger.FieldEntryType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_type", values[i])
			} else if value.Valid {
				_m.EntryType = value.String
			}
		case userbalanceledger.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				_m.Direction = value.String
			}
		case userbalanceledger.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case userbalanceledger.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Float64
			}
		case userbalanceledger.FieldMemo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field memo", values[i])
			} else if value.Valid {
				_m.Memo = new(string)
				*_m.Memo = value.String
			}
		case userbalanceledger.FieldFrozen:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field frozen", values[i])
			} else if value.Valid {
				_m.Frozen = value.Bool
			}
		case userbalanceledger.FieldRefundBatchID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_batch_id", values[i])
			} else if value.Valid {
				_m.RefundBatchID = new(string)
				*_m.RefundBatchID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserBalanceLedger.
// This includes values selected through modifiers, order, etc.
func (_m *UserBalanceLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserBalanceLedger entity.
func (_m *UserBalanceLedger) QueryUser() *UserQuery {
	return NewUserBalanceLedgerClient(_m.config).QueryUser(_m)
}

// QueryOrder queries the "order" edge of the UserBalanceLedger entity.
func (_m *UserBalanceLedger) QueryOrder() *PaymentOrderQuery {
	return NewUserBalanceLedgerClient(_m.config).QueryOrder(_m)
}

// Update returns a builder for updating this UserBalanceLedger.
// Note that you need to call UserBalanceLedger.Unwrap() before calling this method if this UserBalanceLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserBalanceLedger) Update() *UserBalanceLedgerUpdateOne {
	return NewUserBalanceLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserBalanceLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserBalanceLedger) Unwrap() *UserBalanceLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserBalanceLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserBalanceLedger) String() string {
	var builder strings.Builder
	builder.WriteString("UserBalanceLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("entry_type=")
	builder.WriteString(_m.EntryType)
	builder.WriteString(", ")
	builder.WriteString("direction=")
	builder.WriteString(_m.Direction)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	if v := _m.Memo; v != nil {
		builder.WriteString("memo=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("frozen=")
	builder.WriteString(fmt.Sprintf("%v", _m.Frozen))
	builder.WriteString(", ")
	if v := _m.RefundBatchID; v != nil {
		builder.WriteString("refund_batch_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserBalanceLedgers is a parsable slice of UserBalanceLedger.
type UserBalanceLedgers []*UserBalanceLedger
