// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userbalanceledger"
)

// UserBalanceLedgerCreate is the builder for creating a UserBalanceLedger entity.
type UserBalanceLedgerCreate struct {
	config
	mutation *UserBalanceLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserBalanceLedgerCreate) SetCreatedAt(v time.Time) *UserBalanceLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableCreatedAt(v *time.Time) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserBalanceLedgerCreate) SetUpdatedAt(v time.Time) *UserBalanceLedgerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableUpdatedAt(v *time.Time) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserBalanceLedgerCreate) SetUserID(v int64) *UserBalanceLedgerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *UserBalanceLedgerCreate) SetOrderID(v int64) *UserBalanceLedgerCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetEntryType sets the "entry_type" field.
func (_c *UserBalanceLedgerCreate) SetEntryType(v string) *UserBalanceLedgerCreate {
	_c.mutation.SetEntryType(v)
	return _c
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableEntryType(v *string) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetEntryType(*v)
	}
	return _c
}

// SetDirection sets the "direction" field.
func (_c *UserBalanceLedgerCreate) SetDirection(v string) *UserBalanceLedgerCreate {
	_c.mutation.SetDirection(v)
	return _c
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableDirection(v *string) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetDirection(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *UserBalanceLedgerCreate) SetAmount(v float64) *UserBalanceLedgerCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableAmount(v *float64) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *UserBalanceLedgerCreate) SetBalanceAfter(v float64) *UserBalanceLedgerCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableBalanceAfter(v *float64) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetMemo sets the "memo" field.
func (_c *UserBalanceLedgerCreate) SetMemo(v string) *UserBalanceLedgerCreate {
	_c.mutation.SetMemo(v)
	return _c
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableMemo(v *string) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetMemo(*v)
	}
	return _c
}

// SetFrozen sets the "frozen" field.
func (_c *UserBalanceLedgerCreate) SetFrozen(v bool) *UserBalanceLedgerCreate {
	_c.mutation.SetFrozen(v)
	return _c
}

// SetNillableFrozen sets the "frozen" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableFrozen(v *bool) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetFrozen(*v)
	}
	return _c
}

// SetRefundBatchID sets the "refund_batch_id" field.
func (_c *UserBalanceLedgerCreate) SetRefundBatchID(v string) *UserBalanceLedgerCreate {
	_c.mutation.SetRefundBatchID(v)
	return _c
}

// SetNillableRefundBatchID sets the "refund_batch_id" field if the given value is not nil.
func (_c *UserBalanceLedgerCreate) SetNillableRefundBatchID(v *string) *UserBalanceLedgerCreate {
	if v != nil {
		_c.SetRefundBatchID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserBalanceLedgerCreate) SetUser(v *User) *UserBalanceLedgerCreate {
	return _c.SetUserID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_c *UserBalanceLedgerCreate) SetOrder(v *PaymentOrder) *UserBalanceLedgerCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the UserBalanceLedgerMutation object of the builder.
func (_c *UserBalanceLedgerCreate) Mutation() *UserBalanceLedgerMutation {
	return _c.mutation
}

// Save creates the UserBalanceLedger in the database.
func (_c *UserBalanceLedgerCreate) Save(ctx context.Context) (*UserBalanceLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserBalanceLedgerCreate) SaveX(ctx context.Context) *UserBalanceLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBalanceLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBalanceLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserBalanceLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userbalanceledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userbalanceledger.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.EntryType(); !ok {
		v := userbalanceledger.DefaultEntryType
		_c.mutation.SetEntryType(v)
	}
	if _, ok := _c.mutation.Direction(); !ok {
		v := userbalanceledger.DefaultDirection
		_c.mutation.SetDirection(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := userbalanceledger.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		v := userbalanceledger.DefaultBalanceAfter
		_c.mutation.SetBalanceAfter(v)
	}
	if _, ok := _c.mutation.Frozen(); !ok {
		v := userbalanceledger.DefaultFrozen
		_c.mutation.SetFrozen(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserBalanceLedgerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserBalanceLedger.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserBalanceLedger.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserBalanceLedger.user_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "UserBalanceLedger.order_id"`)}
	}
	if _, ok := _c.mutation.EntryType(); !ok {
		return &ValidationError{Name: "entry_type", err: errors.New(`ent: missing required field "UserBalanceLedger.entry_type"`)}
	}
	if v, ok := _c.mutation.EntryType(); ok {
		if err := userbalanceledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.entry_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "UserBalanceLedger.direction"`)}
	}
	if v, ok := _c.mutation.Direction(); ok {
		if err := userbalanceledger.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.direction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "UserBalanceLedger.amount"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "UserBalanceLedger.balance_after"`)}
	}
	if _, ok := _c.mutation.Frozen(); !ok {
		return &ValidationError{Name: "frozen", err: errors.New(`ent: missing required field "UserBalanceLedger.frozen"`)}
	}
	if v, ok := _c.mutation.RefundBatchID(); ok {
		if err := userbalanceledger.RefundBatchIDValidator(v); err != nil {
			return &ValidationError{Name: "refund_batch_id", err: fmt.Errorf(`ent: validator failed for field "UserBalanceLedger.refund_batch_id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserBalanceLedger.user"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "UserBalanceLedger.order"`)}
	}
	return nil
}

func (_c *UserBalanceLedgerCreate) sqlSave(ctx context.Context) (*UserBalanceLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserBalanceLedgerCreate) createSpec() (*UserBalanceLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &UserBalanceLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userbalanceledger.Table, sqlgraph.NewFieldSpec(userbalanceledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userbalanceledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalanceledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EntryType(); ok {
		_spec.SetField(userbalanceledger.FieldEntryType, field.TypeString, value)
		_node.EntryType = value
	}
	if value, ok := _c.mutation.Direction(); ok {
		_spec.SetField(userbalanceledger.FieldDirection, field.TypeString, value)
		_node.Direction = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(userbalanceledger.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(userbalanceledger.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.Memo(); ok {
		_spec.SetField(userbalanceledger.FieldMemo, field.TypeString, value)
		_node.Memo = &value
	}
	if value, ok := _c.mutation.Frozen(); ok {
		_spec.SetField(userbalanceledger.FieldFrozen, field.TypeBool, value)
		_node.Frozen = value
	}
	if value, ok := _c.mutation.RefundBatchID(); ok {
		_spec.SetField(userbalanceledger.FieldRefundBatchID, field.TypeString, value)
		_node.RefundBatchID = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.UserTable,
			Columns: []string{userbalanceledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbalanceledger.OrderTable,
			Columns: []string{userbalanceledger.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserBalanceLedger.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserBalanceLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserBalanceLedgerCreate) OnConflict(opts ...sql.ConflictOption) *UserBalanceLedgerUpsertOne {
	_c.conflict = opts
	return &UserBalanceLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserBalanceLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserBalanceLedgerCreate) OnConflictColumns(columns ...string) *UserBalanceLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserBalanceLedgerUpsertOne{
		create: _c,
	}
}

type (
	// UserBalanceLedgerUpsertOne is the builder for "upsert"-ing
	//  one UserBalanceLedger node.
	UserBalanceLedgerUpsertOne struct {
		create *UserBalanceLedgerCreate
	}

	// UserBalanceLedgerUpsert is the "OnConflict" setter.
	UserBalanceLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalanceLedgerUpsert) SetUpdatedAt(v time.Time) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateUpdatedAt() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserBalanceLedgerUpsert) SetUserID(v int64) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateUserID() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldUserID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *UserBalanceLedgerUpsert) SetOrderID(v int64) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateOrderID() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldOrderID)
	return u
}

// SetEntryType sets the "entry_type" field.
func (u *UserBalanceLedgerUpsert) SetEntryType(v string) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldEntryType, v)
	return u
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateEntryType() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldEntryType)
	return u
}

// SetDirection sets the "direction" field.
func (u *UserBalanceLedgerUpsert) SetDirection(v string) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldDirection, v)
	return u
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateDirection() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldDirection)
	return u
}

// SetAmount sets the "amount" field.
func (u *UserBalanceLedgerUpsert) SetAmount(v float64) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateAmount() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *UserBalanceLedgerUpsert) AddAmount(v float64) *UserBalanceLedgerUpsert {
	u.Add(userbalanceledger.FieldAmount, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserBalanceLedgerUpsert) SetBalanceAfter(v float64) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateBalanceAfter() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserBalanceLedgerUpsert) AddBalanceAfter(v float64) *UserBalanceLedgerUpsert {
	u.Add(userbalanceledger.FieldBalanceAfter, v)
	return u
}

// SetMemo sets the "memo" field.
func (u *UserBalanceLedgerUpsert) SetMemo(v string) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldMemo, v)
	return u
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateMemo() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldMemo)
	return u
}

// ClearMemo clears the value of the "memo" field.
func (u *UserBalanceLedgerUpsert) ClearMemo() *UserBalanceLedgerUpsert {
	u.SetNull(userbalanceledger.FieldMemo)
	return u
}

// SetFrozen sets the "frozen" field.
func (u *UserBalanceLedgerUpsert) SetFrozen(v bool) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldFrozen, v)
	return u
}

// UpdateFrozen sets the "frozen" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateFrozen() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldFrozen)
	return u
}

// SetRefundBatchID sets the "refund_batch_id" field.
func (u *UserBalanceLedgerUpsert) SetRefundBatchID(v string) *UserBalanceLedgerUpsert {
	u.Set(userbalanceledger.FieldRefundBatchID, v)
	return u
}

// UpdateRefundBatchID sets the "refund_batch_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsert) UpdateRefundBatchID() *UserBalanceLedgerUpsert {
	u.SetExcluded(userbalanceledger.FieldRefundBatchID)
	return u
}

// ClearRefundBatchID clears the value of the "refund_batch_id" field.
func (u *UserBalanceLedgerUpsert) ClearRefundBatchID() *UserBalanceLedgerUpsert {
	u.SetNull(userbalanceledger.FieldRefundBatchID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserBalanceLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserBalanceLedgerUpsertOne) UpdateNewValues() *UserBalanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userbalanceledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserBalanceLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserBalanceLedgerUpsertOne) Ignore() *UserBalanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserBalanceLedgerUpsertOne) DoNothing() *UserBalanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserBalanceLedgerCreate.OnConflict
// documentation for more info.
func (u *UserBalanceLedgerUpsertOne) Update(set func(*UserBalanceLedgerUpsert)) *UserBalanceLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserBalanceLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalanceLedgerUpsertOne) SetUpdatedAt(v time.Time) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateUpdatedAt() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserBalanceLedgerUpsertOne) SetUserID(v int64) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateUserID() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *UserBalanceLedgerUpsertOne) SetOrderID(v int64) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateOrderID() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateOrderID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *UserBalanceLedgerUpsertOne) SetEntryType(v string) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateEntryType() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetDirection sets the "direction" field.
func (u *UserBalanceLedgerUpsertOne) SetDirection(v string) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateDirection() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateDirection()
	})
}

// SetAmount sets the "amount" field.
func (u *UserBalanceLedgerUpsertOne) SetAmount(v float64) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserBalanceLedgerUpsertOne) AddAmount(v float64) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateAmount() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserBalanceLedgerUpsertOne) SetBalanceAfter(v float64) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserBalanceLedgerUpsertOne) AddBalanceAfter(v float64) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateBalanceAfter() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetMemo sets the "memo" field.
func (u *UserBalanceLedgerUpsertOne) SetMemo(v string) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateMemo() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *UserBalanceLedgerUpsertOne) ClearMemo() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.ClearMemo()
	})
}

// SetFrozen sets the "frozen" field.
func (u *UserBalanceLedgerUpsertOne) SetFrozen(v bool) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetFrozen(v)
	})
}

// UpdateFrozen sets the "frozen" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateFrozen() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateFrozen()
	})
}

// SetRefundBatchID sets the "refund_batch_id" field.
func (u *UserBalanceLedgerUpsertOne) SetRefundBatchID(v string) *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetRefundBatchID(v)
	})
}

// UpdateRefundBatchID sets the "refund_batch_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertOne) UpdateRefundBatchID() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateRefundBatchID()
	})
}

// ClearRefundBatchID clears the value of the "refund_batch_id" field.
func (u *UserBalanceLedgerUpsertOne) ClearRefundBatchID() *UserBalanceLedgerUpsertOne {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.ClearRefundBatchID()
	})
}

// Exec executes the query.
func (u *UserBalanceLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserBalanceLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserBalanceLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserBalanceLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserBalanceLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserBalanceLedgerCreateBulk is the builder for creating many UserBalanceLedger entities in bulk.
type UserBalanceLedgerCreateBulk struct {
	config
	err      error
	builders []*UserBalanceLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the UserBalanceLedger entities in the database.
func (_c *UserBalanceLedgerCreateBulk) Save(ctx context.Context) ([]*UserBalanceLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserBalanceLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserBalanceLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserBalanceLedgerCreateBulk) SaveX(ctx context.Context) []*UserBalanceLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserBalanceLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserBalanceLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserBalanceLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserBalanceLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserBalanceLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserBalanceLedgerUpsertBulk {
	_c.conflict = opts
	return &UserBalanceLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserBalanceLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserBalanceLedgerCreateBulk) OnConflictColumns(columns ...string) *UserBalanceLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserBalanceLedgerUpsertBulk{
		create: _c,
	}
}

// UserBalanceLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of UserBalanceLedger nodes.
type UserBalanceLedgerUpsertBulk struct {
	create *UserBalanceLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserBalanceLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserBalanceLedgerUpsertBulk) UpdateNewValues() *UserBalanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userbalanceledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserBalanceLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserBalanceLedgerUpsertBulk) Ignore() *UserBalanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserBalanceLedgerUpsertBulk) DoNothing() *UserBalanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserBalanceLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *UserBalanceLedgerUpsertBulk) Update(set func(*UserBalanceLedgerUpsert)) *UserBalanceLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserBalanceLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserBalanceLedgerUpsertBulk) SetUpdatedAt(v time.Time) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateUpdatedAt() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserBalanceLedgerUpsertBulk) SetUserID(v int64) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateUserID() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *UserBalanceLedgerUpsertBulk) SetOrderID(v int64) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateOrderID() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateOrderID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *UserBalanceLedgerUpsertBulk) SetEntryType(v string) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateEntryType() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetDirection sets the "direction" field.
func (u *UserBalanceLedgerUpsertBulk) SetDirection(v string) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetDirection(v)
	})
}

// UpdateDirection sets the "direction" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateDirection() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateDirection()
	})
}

// SetAmount sets the "amount" field.
func (u *UserBalanceLedgerUpsertBulk) SetAmount(v float64) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *UserBalanceLedgerUpsertBulk) AddAmount(v float64) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateAmount() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateAmount()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *UserBalanceLedgerUpsertBulk) SetBalanceAfter(v float64) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *UserBalanceLedgerUpsertBulk) AddBalanceAfter(v float64) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateBalanceAfter() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetMemo sets the "memo" field.
func (u *UserBalanceLedgerUpsertBulk) SetMemo(v string) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetMemo(v)
	})
}

// UpdateMemo sets the "memo" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateMemo() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateMemo()
	})
}

// ClearMemo clears the value of the "memo" field.
func (u *UserBalanceLedgerUpsertBulk) ClearMemo() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.ClearMemo()
	})
}

// SetFrozen sets the "frozen" field.
func (u *UserBalanceLedgerUpsertBulk) SetFrozen(v bool) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetFrozen(v)
	})
}

// UpdateFrozen sets the "frozen" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateFrozen() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateFrozen()
	})
}

// SetRefundBatchID sets the "refund_batch_id" field.
func (u *UserBalanceLedgerUpsertBulk) SetRefundBatchID(v string) *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.SetRefundBatchID(v)
	})
}

// UpdateRefundBatchID sets the "refund_batch_id" field to the value that was provided on create.
func (u *UserBalanceLedgerUpsertBulk) UpdateRefundBatchID() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.UpdateRefundBatchID()
	})
}

// ClearRefundBatchID clears the value of the "refund_batch_id" field.
func (u *UserBalanceLedgerUpsertBulk) ClearRefundBatchID() *UserBalanceLedgerUpsertBulk {
	return u.Update(func(s *UserBalanceLedgerUpsert) {
		s.ClearRefundBatchID()
	})
}

// Exec executes the query.
func (u *UserBalanceLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserBalanceLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserBalanceLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserBalanceLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
