// Code generated by ent, DO NOT EDIT.

package userbalanceledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userbalanceledger type in the database.
	Label = "user_balance_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldEntryType holds the string denoting the entry_type field in the database.
	FieldEntryType = "entry_type"
	// FieldDirection holds the string denoting the direction field in the database.
	FieldDirection = "direction"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldMemo holds the string denoting the memo field in the database.
	FieldMemo = "memo"
	// FieldFrozen holds the string denoting the frozen field in the database.
	FieldFrozen = "frozen"
	// FieldRefundBatchID holds the string denoting the refund_batch_id field in the database.
	FieldRefundBatchID = "refund_batch_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// Table holds the table name of the userbalanceledger in the database.
	Table = "user_balance_ledger"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_balance_ledger"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// OrderTable is the table that holds the order relation/edge.
	OrderTable = "user_balance_ledger"
	// OrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	OrderInverseTable = "payment_orders"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "order_id"
)

// Columns holds all SQL columns for userbalanceledger fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldOrderID,
	FieldEntryType,
	FieldDirection,
	FieldAmount,
	FieldBalanceAfter,
	FieldMemo,
	FieldFrozen,
	FieldRefundBatchID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEntryType holds the default value on creation for the "entry_type" field.
	DefaultEntryType string
	// EntryTypeValidator is a validator for the "entry_type" field. It is called by the builders before save.
	EntryTypeValidator func(string) error
	// DefaultDirection holds the default value on creation for the "direction" field.
	DefaultDirection string
	// DirectionValidator is a validator for the "direction" field. It is called by the builders before save.
	DirectionValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultBalanceAfter holds the default value on creation for the "balance_after" field.
	DefaultBalanceAfter float64
	// DefaultFrozen holds the default value on creation for the "frozen" field.
	DefaultFrozen bool
	// RefundBatchIDValidator is a validator for the "refund_batch_id" field. It is called by the builders before save.
	RefundBatchIDValidator func(string) error
)

// OrderOption defines the ordering options for the UserBalanceLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByEntryType orders the results by the entry_type field.
func ByEntryType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryType, opts...).ToFunc()
}

// ByDirection orders the results by the direction field.
func ByDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirection, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByMemo orders the results by the memo field.
func ByMemo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemo, opts...).ToFunc()
}

// ByFrozen orders the results by the frozen field.
func ByFrozen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozen, opts...).ToFunc()
}

// ByRefundBatchID orders the results by the refund_batch_id field.
func ByRefundBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundBatchID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrderField orders the results by order field.
func ByOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OrderTable, OrderColumn),
	)
}
