// Code generated by ent, DO NOT EDIT.

package userbalanceledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldUserID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldOrderID, v))
}

// EntryType applies equality check predicate on the "entry_type" field. It's identical to EntryTypeEQ.
func EntryType(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldEntryType, v))
}

// Direction applies equality check predicate on the "direction" field. It's identical to DirectionEQ.
func Direction(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldDirection, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldAmount, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// Memo applies equality check predicate on the "memo" field. It's identical to MemoEQ.
func Memo(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldMemo, v))
}

// Frozen applies equality check predicate on the "frozen" field. It's identical to FrozenEQ.
func Frozen(v bool) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldFrozen, v))
}

// RefundBatchID applies equality check predicate on the "refund_batch_id" field. It's identical to RefundBatchIDEQ.
func RefundBatchID(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldRefundBatchID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldUserID, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldOrderID, vs...))
}

// EntryTypeEQ applies the EQ predicate on the "entry_type" field.
func EntryTypeEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldEntryType, v))
}

// EntryTypeNEQ applies the NEQ predicate on the "entry_type" field.
func EntryTypeNEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldEntryType, v))
}

// EntryTypeIn applies the In predicate on the "entry_type" field.
func EntryTypeIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldEntryType, vs...))
}

// EntryTypeNotIn applies the NotIn predicate on the "entry_type" field.
func EntryTypeNotIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldEntryType, vs...))
}

// EntryTypeGT applies the GT predicate on the "entry_type" field.
func EntryTypeGT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldEntryType, v))
}

// EntryTypeGTE applies the GTE predicate on the "entry_type" field.
func EntryTypeGTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldEntryType, v))
}

// EntryTypeLT applies the LT predicate on the "entry_type" field.
func EntryTypeLT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldEntryType, v))
}

// EntryTypeLTE applies the LTE predicate on the "entry_type" field.
func EntryTypeLTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldEntryType, v))
}

// EntryTypeContains applies the Contains predicate on the "entry_type" field.
func EntryTypeContains(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContains(FieldEntryType, v))
}

// EntryTypeHasPrefix applies the HasPrefix predicate on the "entry_type" field.
func EntryTypeHasPrefix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasPrefix(FieldEntryType, v))
}

// EntryTypeHasSuffix applies the HasSuffix predicate on the "entry_type" field.
func EntryTypeHasSuffix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasSuffix(FieldEntryType, v))
}

// EntryTypeEqualFold applies the EqualFold predicate on the "entry_type" field.
func EntryTypeEqualFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEqualFold(FieldEntryType, v))
}

// EntryTypeContainsFold applies the ContainsFold predicate on the "entry_type" field.
func EntryTypeContainsFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContainsFold(FieldEntryType, v))
}

// DirectionEQ applies the EQ predicate on the "direction" field.
func DirectionEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldDirection, v))
}

// DirectionNEQ applies the NEQ predicate on the "direction" field.
func DirectionNEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldDirection, v))
}

// DirectionIn applies the In predicate on the "direction" field.
func DirectionIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldDirection, vs...))
}

// DirectionNotIn applies the NotIn predicate on the "direction" field.
func DirectionNotIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldDirection, vs...))
}

// DirectionGT applies the GT predicate on the "direction" field.
func DirectionGT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldDirection, v))
}

// DirectionGTE applies the GTE predicate on the "direction" field.
func DirectionGTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldDirection, v))
}

// DirectionLT applies the LT predicate on the "direction" field.
func DirectionLT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldDirection, v))
}

// DirectionLTE applies the LTE predicate on the "direction" field.
func DirectionLTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldDirection, v))
}

// DirectionContains applies the Contains predicate on the "direction" field.
func DirectionContains(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContains(FieldDirection, v))
}

// DirectionHasPrefix applies the HasPrefix predicate on the "direction" field.
func DirectionHasPrefix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasPrefix(FieldDirection, v))
}

// DirectionHasSuffix applies the HasSuffix predicate on the "direction" field.
func DirectionHasSuffix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasSuffix(FieldDirection, v))
}

// DirectionEqualFold applies the EqualFold predicate on the "direction" field.
func DirectionEqualFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEqualFold(FieldDirection, v))
}

// DirectionContainsFold applies the ContainsFold predicate on the "direction" field.
func DirectionContainsFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContainsFold(FieldDirection, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldAmount, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v float64) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldBalanceAfter, v))
}

// MemoEQ applies the EQ predicate on the "memo" field.
func MemoEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldMemo, v))
}

// MemoNEQ applies the NEQ predicate on the "memo" field.
func MemoNEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldMemo, v))
}

// MemoIn applies the In predicate on the "memo" field.
func MemoIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldMemo, vs...))
}

// MemoNotIn applies the NotIn predicate on the "memo" field.
func MemoNotIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldMemo, vs...))
}

// MemoGT applies the GT predicate on the "memo" field.
func MemoGT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldMemo, v))
}

// MemoGTE applies the GTE predicate on the "memo" field.
func MemoGTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldMemo, v))
}

// MemoLT applies the LT predicate on the "memo" field.
func MemoLT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldMemo, v))
}

// MemoLTE applies the LTE predicate on the "memo" field.
func MemoLTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldMemo, v))
}

// MemoContains applies the Contains predicate on the "memo" field.
func MemoContains(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContains(FieldMemo, v))
}

// MemoHasPrefix applies the HasPrefix predicate on the "memo" field.
func MemoHasPrefix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasPrefix(FieldMemo, v))
}

// MemoHasSuffix applies the HasSuffix predicate on the "memo" field.
func MemoHasSuffix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasSuffix(FieldMemo, v))
}

// MemoIsNil applies the IsNil predicate on the "memo" field.
func MemoIsNil() predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIsNull(FieldMemo))
}

// MemoNotNil applies the NotNil predicate on the "memo" field.
func MemoNotNil() predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotNull(FieldMemo))
}

// MemoEqualFold applies the EqualFold predicate on the "memo" field.
func MemoEqualFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEqualFold(FieldMemo, v))
}

// MemoContainsFold applies the ContainsFold predicate on the "memo" field.
func MemoContainsFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContainsFold(FieldMemo, v))
}

// FrozenEQ applies the EQ predicate on the "frozen" field.
func FrozenEQ(v bool) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldFrozen, v))
}

// FrozenNEQ applies the NEQ predicate on the "frozen" field.
func FrozenNEQ(v bool) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldFrozen, v))
}

// RefundBatchIDEQ applies the EQ predicate on the "refund_batch_id" field.
func RefundBatchIDEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEQ(FieldRefundBatchID, v))
}

// RefundBatchIDNEQ applies the NEQ predicate on the "refund_batch_id" field.
func RefundBatchIDNEQ(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNEQ(FieldRefundBatchID, v))
}

// RefundBatchIDIn applies the In predicate on the "refund_batch_id" field.
func RefundBatchIDIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIn(FieldRefundBatchID, vs...))
}

// RefundBatchIDNotIn applies the NotIn predicate on the "refund_batch_id" field.
func RefundBatchIDNotIn(vs ...string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotIn(FieldRefundBatchID, vs...))
}

// RefundBatchIDGT applies the GT predicate on the "refund_batch_id" field.
func RefundBatchIDGT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGT(FieldRefundBatchID, v))
}

// RefundBatchIDGTE applies the GTE predicate on the "refund_batch_id" field.
func RefundBatchIDGTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldGTE(FieldRefundBatchID, v))
}

// RefundBatchIDLT applies the LT predicate on the "refund_batch_id" field.
func RefundBatchIDLT(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLT(FieldRefundBatchID, v))
}

// RefundBatchIDLTE applies the LTE predicate on the "refund_batch_id" field.
func RefundBatchIDLTE(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldLTE(FieldRefundBatchID, v))
}

// RefundBatchIDContains applies the Contains predicate on the "refund_batch_id" field.
func RefundBatchIDContains(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContains(FieldRefundBatchID, v))
}

// RefundBatchIDHasPrefix applies the HasPrefix predicate on the "refund_batch_id" field.
func RefundBatchIDHasPrefix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasPrefix(FieldRefundBatchID, v))
}

// RefundBatchIDHasSuffix applies the HasSuffix predicate on the "refund_batch_id" field.
func RefundBatchIDHasSuffix(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldHasSuffix(FieldRefundBatchID, v))
}

// RefundBatchIDIsNil applies the IsNil predicate on the "refund_batch_id" field.
func RefundBatchIDIsNil() predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldIsNull(FieldRefundBatchID))
}

// RefundBatchIDNotNil applies the NotNil predicate on the "refund_batch_id" field.
func RefundBatchIDNotNil() predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldNotNull(FieldRefundBatchID))
}

// RefundBatchIDEqualFold applies the EqualFold predicate on the "refund_batch_id" field.
func RefundBatchIDEqualFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldEqualFold(FieldRefundBatchID, v))
}

// RefundBatchIDContainsFold applies the ContainsFold predicate on the "refund_batch_id" field.
func RefundBatchIDContainsFold(v string) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.FieldContainsFold(FieldRefundBatchID, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.PaymentOrder) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserBalanceLedger) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserBalanceLedger) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserBalanceLedger) predicate.UserBalanceLedger {
	return predicate.UserBalanceLedger(sql.NotPredicates(p))
}
